In [ ]:
##### IPL Win Probability Predictor, End To End Machine Learning Problem. ######
##### Team members: Raghavendra K H (23M0013), J Ramakrishna (23M0024), Sujan D Silva (23M0011) ########

In [398]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split

In [399]:
df= pd.read_excel('C:\\Users\\admin\\OneDrive\\Desktop\\ML\\Data File.xlsx')
df

Toss winner Toss decision Venue(Home/Away) Result
0    Royal Challengers Bangalore         field             Away   Lose
1        Rising Pune Supergiants         field             Home    Win
2          Kolkata Knight Riders         field             Away    Win
3                Kings XI Punjab         field             Away    Win
4    Royal Challengers Bangalore           bat             Home    Win
..                           ...           ...              ...    ...
751               Mumbai Indians         field             Home    Win
752          Chennai Super Kings           bat             Home   Lose
753               Delhi Capitals         field             Away    Win
754          Chennai Super Kings         field             Away    Win
755               Mumbai Indians           bat             Away    Win

[756 rows x 4 columns]

In [400]:
#Label encoding and One hot encoding
encoded_df = pd.get_dummies(df['Toss winner'], prefix='Toss winner')
df_encoded = pd.concat([encoded_df, df], axis=1)
df_encoded = df_encoded.drop(columns=['Toss winner'])

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df_encoded = df_encoded.apply(label_encoder.fit_transform)

pd.DataFrame(df_encoded)

Toss winner_Chennai Super Kings  Toss winner_Deccan Chargers  \
0                                  0                            0   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   
..                               ...                          ...   
751                                0                            0   
752                                1                            0   
753                                0                            0   
754                                1                            0   
755                                0                            0   

     Toss winner_Delhi Capitals  Toss winner_Delhi Daredevils  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   
..                          ...                           ...   
751                           0                             0   
752                           0                             0   
753                           1                             0   
754                           0                             0   
755                           0                             0   

     Toss winner_Gujarat Lions  Toss winner_Kings XI Punjab  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            1   
4                            0                            0   
..                         ...                          ...   
751                          0                            0   
752                          0                            0   
753                          0                            0   
754                          0                            0   
755                          0                            0   

     Toss winner_Kochi Tuskers Kerala  Toss winner_Kolkata Knight Riders  \
0                                   0                                  0   
1                                   0                                  0   
2                                   0                                  1   
3                                   0                                  0   
4                                   0                                  0   
..                                ...                                ...   
751                                 0                                  0   
752                                 0                                  0   
753                                 0                                  0   
754                                 0                                  0   
755                                 0                                  0   

     Toss winner_Mumbai Indians  Toss winner_Pune Warriors  \
0                             0                          0   
1                             0                          0   
2                             0                          0   
3                             0                          0   
4                             0                          0   
..                          ...                        ...   
751                           1                          0   
752                           0                          0   
753                           0                          0   
754                           0                          0   
755                           1            

In [488]:
#Creating x and y
x = df_encoded.iloc[:, :-1]
y = df_encoded.iloc[:, -1].values
y

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [402]:
#Creating train data and test data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2)
x_test

Toss winner_Chennai Super Kings  Toss winner_Deccan Chargers  \
247                                1                            0   
171                                0                            1   
533                                0                            0   
417                                0                            0   
92                                 0                            0   
..                               ...                          ...   
725                                0                            0   
321                                0                            0   
181                                1                            0   
234                                1                            0   
104                                0                            0   

     Toss winner_Delhi Capitals  Toss winner_Delhi Daredevils  \
247                           0                             0   
171                           0                             0   
533                           0                             0   
417                           0                             0   
92                            0                             0   
..                          ...                           ...   
725                           0                             0   
321                           0                             0   
181                           0                             0   
234                           0                             0   
104                           0                             0   

     Toss winner_Gujarat Lions  Toss winner_Kings XI Punjab  \
247                          0                            0   
171                          0                            0   
533                          0                            0   
417                          0                            0   
92                           0                            0   
..                         ...                          ...   
725                          0                            0   
321                          0                            0   
181                          0                            0   
234                          0                            0   
104                          0                            0   

     Toss winner_Kochi Tuskers Kerala  Toss winner_Kolkata Knight Riders  \
247                                 0                                  0   
171                                 0                                  0   
533                                 0                                  0   
417                                 0                                  1   
92                                  0                                  0   
..                                ...                                ...   
725                                 0                                  0   
321                                 0                                  0   
181                                 0                                  0   
234                                 0                                  0   
104                                 0                                  0   

     Toss winner_Mumbai Indians  Toss winner_Pune Warriors  \
247                           0                          0   
171                           0                          0   
533                           0                          0   
417                           0                          0   
92                            0                          0   
..                          ...                        ...   
725                           0                          0   
321                           0                          0   
181                           0                          0   
234                           0                          0   
104                           0            

In [403]:
########## The SVC model (rbf kernel) ##########

from sklearn.svm import SVC
classifier_rbf = SVC (kernel = 'rbf', gamma = 2, C=10)
classifier_rbf.fit (x_train,y_train)

SVC(C=10, gamma=2)

In [404]:
#The predicted data for the test data
y_pred = classifier_rbf.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [405]:
#The predicted values by the model for the entire data
Y_pred= classifier_rbf.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             0  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [586]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test , y_pred))

0.625


In [587]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[37 29]
 [28 58]]


In [491]:
########## The SVC model (polynomial kernel) ##########

from sklearn.svm import SVC
classifier_poly = SVC (kernel = 'poly', degree = 4,  gamma = 0.6, C=10)
classifier_poly.fit (x_train,y_train)

SVC(C=10, degree=4, gamma=0.6, kernel='poly')

In [496]:
#The predicted data for the test data
y_pred = classifier_poly.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [497]:
#The predicted values by the model for the entire data
Y_pred= classifier_poly.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             0  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [515]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test ,y_pred))

0.618421052631579


In [516]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[38 28]
 [30 56]]


In [500]:
########## The SVC model (sigmoid kernel) ##########

from sklearn.svm import SVC
classifier_sig = SVC (kernel = 'sigmoid',  gamma = 0.6, C=10)
classifier_sig.fit (x_train,y_train)

SVC(C=10, gamma=0.6, kernel='sigmoid')

In [503]:
#The predicted data for the test data
y_pred = classifier_sig.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [504]:
#The predicted values by the model for the entire data
Y_pred= classifier_sig.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
751           0  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [513]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test, y_pred))

0.618421052631579


In [514]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[38 28]
 [30 56]]


In [518]:
########### Logistic Regression Model #########

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit (x_train,y_train )

LogisticRegression()

In [519]:
#The predicted data for the test data
y_pred = lr.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [520]:
#The predicted values by the model for the entire data
Y_pred= lr.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [521]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test, y_pred))

0.618421052631579


In [522]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[38 28]
 [30 56]]


In [523]:
########## The KNN Model ###########

from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_knn = sc_x.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train_knn ,x_test_knn ,y_train_knn ,y_test_knn  = train_test_split(x_knn ,y ,test_size= 0.2)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p= 2)
knn.fit(x_train_knn ,y_train_knn)

KNeighborsClassifier(n_neighbors=15)

In [524]:
#The predicted data for the test data
y_pred_knn = knn.predict(x_test_knn)
print (y_pred_knn)

[0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0
 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0
 1 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0
 1 1 1 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1
 0 0 1 0]


In [525]:
#The predicted values by the model for the entire data
Y_pred_knn= knn.predict(x_knn)

#The predicted data for the entire model
df_ypred_knn = pd.DataFrame(Y_pred_knn,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred_knn],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           0  
755           1  

[756 rows x 5 columns]

In [526]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test_knn, y_pred_knn))

0.5526315789473685


In [527]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test_knn, y_pred_knn)
print (cm)

[[40 31]
 [37 44]]


In [428]:
######### Naive Bayes Model (Gaussian NB) ##########

from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit (x_train, y_train)

GaussianNB()

In [528]:
#The predicted data for the test data
y_pred = GNB.predict(x_test)
print (y_pred)

[1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0
 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 0 1 0 1 1 0 1
 0 1 1 0]


In [529]:
#The predicted values by the model for the entire data
Y_pred= GNB.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             1  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           1  

[756 rows x 5 columns]

In [530]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5789473684210527


In [531]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[34 32]
 [32 54]]


In [532]:
######### Naive Bayes Model (Bernaulli NB)

from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(x_train,y_train)

BernoulliNB()

In [533]:
#The predicted data for the test data
y_pred = BNB.predict(x_test)
print (y_pred)

[1 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0
 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 0
 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 1 1 1 1
 0 1 1 0]


In [534]:
#The predicted values by the model for the entire data
Y_pred= BNB.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             1  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           1  

[756 rows x 5 columns]

In [535]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.625


In [437]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[37 29]
 [28 58]]


In [536]:
######### Naive Bayes Model (Multinomial NB)

from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(x_train,y_train)

MultinomialNB()

In [537]:
#The predicted data for the test data
y_pred = MNB.predict(x_test)
print (y_pred)

[1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0
 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 0
 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 0 1 0 1 1 0 1
 0 1 1 0]


In [538]:
#The predicted values by the model for the entire data
Y_pred= BNB.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             1  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           1  

[756 rows x 5 columns]

In [539]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5723684210526315


In [540]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[34 32]
 [33 53]]


In [443]:
############ Decision Tree Classifier (criterion = 'entropy') #############

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier (criterion = 'entropy')
dtc.fit (x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [541]:
#The predicted data for the test data
y_pred = dtc.predict(x_test)
print (y_pred)

[1 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 1 1 0
 0 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1
 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1
 0 0 1 0]


In [542]:
#The predicted values by the model for the entire data
Y_pred= dtc.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             0  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [543]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5131578947368421


In [544]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[33 33]
 [41 45]]


In [545]:
########### Decision Tree Classifier (criterion = 'gini')

from sklearn.tree import DecisionTreeClassifier
dtc_g = DecisionTreeClassifier (criterion = 'gini')
dtc_g.fit (x_train, y_train)

DecisionTreeClassifier()

In [546]:
#The predicted data for the test data
y_pred = dtc_g.predict(x_test)
print (y_pred)

[1 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 1 1 0
 0 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1
 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1
 0 0 1 0]


In [547]:
#The predicted values by the model for the entire data
Y_pred= dtc_g.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             0  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [549]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5131578947368421


In [550]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[33 33]
 [41 45]]


In [551]:
############# Random Forest Classifier ##############

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100, criterion='entropy')
rfc.fit (x_train,y_train)

RandomForestClassifier(criterion='entropy')

In [552]:
#The predicted data for the test data
y_pred = rfc.predict(x_test)
print (y_pred)

[1 1 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0
 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1
 1 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 1
 0 0 1 0]


In [553]:
#The predicted values by the model for the entire data
Y_pred= rfc.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             0  
3             1  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [554]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5263157894736842


In [555]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[30 36]
 [36 50]]


In [556]:
########## AdaBoosting Algorithm (basemodel: Decision Tree) ###########

from sklearn.ensemble import AdaBoostClassifier
model = DecisionTreeClassifier (criterion = 'entropy', max_depth =1)
AdaBoost= AdaBoostClassifier(base_estimator = model, n_estimators = 10, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [557]:
y_pred= boostmodel.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [558]:
#The predicted values by the model for the entire data
Y_pred= boostmodel.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           1  

[756 rows x 5 columns]

In [559]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.6052631578947368


In [560]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[27 39]
 [21 65]]


In [561]:
########## AdaBoosting Algorithm (basemodel: Random Forest) ###########

from sklearn.ensemble import AdaBoostClassifier
model = RandomForestClassifier (criterion = 'entropy', max_depth =1)
AdaBoost= AdaBoostClassifier(base_estimator = model, n_estimators = 10, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [562]:
y_pred= boostmodel.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [563]:
#The predicted values by the model for the entire data
Y_pred= boostmodel.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           1  

[756 rows x 5 columns]

In [564]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.625


In [565]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[37 29]
 [28 58]]


In [566]:
########## AdaBoosting Algorithm (basemodel: Multinomial Naive Bayce) ###########

from sklearn.ensemble import AdaBoostClassifier
model = MultinomialNB()
AdaBoost= AdaBoostClassifier(base_estimator = model, n_estimators = 10, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [567]:
y_pred= boostmodel.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1])

In [568]:
#The predicted values by the model for the entire data
Y_pred= boostmodel.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           1  

[756 rows x 5 columns]

In [569]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5855263157894737


In [570]:
########## AdaBoosting Algorithm (basemodel: Bernaulli Naive Bayce) ###########

from sklearn.ensemble import AdaBoostClassifier
model = BernoulliNB()
AdaBoost= AdaBoostClassifier(base_estimator = model, n_estimators = 10, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [571]:
y_pred= boostmodel.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [572]:
#The predicted values by the model for the entire data
Y_pred= boostmodel.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
751           0  
752           0  
753           0  
754           0  
755           0  

[756 rows x 5 columns]

In [573]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.4342105263157895


In [574]:
########## AdaBoosting Algorithm (basemodel: Gaussian Naive Bayce) ###########

from sklearn.ensemble import AdaBoostClassifier
model = GaussianNB()
AdaBoost= AdaBoostClassifier(base_estimator = model, n_estimators = 10, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [575]:
y_pred= boostmodel.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [576]:
#The predicted values by the model for the entire data
Y_pred= boostmodel.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
751           0  
752           0  
753           0  
754           0  
755           0  

[756 rows x 5 columns]

In [577]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.4342105263157895


In [578]:
########## AdaBoosting Algorithm (basemodel: Logistic Regression) ###########

from sklearn.ensemble import AdaBoostClassifier
model = LogisticRegression()
AdaBoost= AdaBoostClassifier(base_estimator = model, n_estimators = 10, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [579]:
y_pred= boostmodel.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1])

In [580]:
#The predicted values by the model for the entire data
Y_pred= boostmodel.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

Toss winner Toss decision Venue(Home/Away)  Result  \
0    Royal Challengers Bangalore         field             Away       0   
1        Rising Pune Supergiants         field             Home       1   
2          Kolkata Knight Riders         field             Away       1   
3                Kings XI Punjab         field             Away       1   
4    Royal Challengers Bangalore           bat             Home       1   
..                           ...           ...              ...     ...   
751               Mumbai Indians         field             Home       1   
752          Chennai Super Kings           bat             Home       0   
753               Delhi Capitals         field             Away       1   
754          Chennai Super Kings         field             Away       1   
755               Mumbai Indians           bat             Away       1   

     Prediction  
0             1  
1             1  
2             1  
3             0  
4             0  
..          ...  
751           1  
752           1  
753           1  
754           1  
755           0  

[756 rows x 5 columns]

In [581]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.5855263157894737


In [582]:
########## THE CHOSEN MODEL ###########
######### Naive Bayes Model (Bernaulli NB) ########

from sklearn.naive_bayes import BernoulliNB
boostmodel_chosen = BernoulliNB()
boostmodel_chosen.fit(x_train,y_train)
 

y_pred= boostmodel_chosen.predict(x_test)
y_pred

#The predicted values by the model for the entire data
Y_pred= boostmodel_chosen.predict(x)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([df.iloc[:, :-1], df_encoded['Result'], df_ypred],axis = 1 ))
result

#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.625


In [585]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the trained model
model = boostmodel_chosen

# Function to preprocess input data
def preprocess_input(toss_winner, toss_decision, venue):
    # One-hot encoding for toss winner
    toss_winner_encoded = pd.get_dummies(pd.Series(toss_winner)).reindex(columns=teams, fill_value=0)
    
    # Label encoding for toss decision and venue
    toss_decision_encoded = label_encoder_toss_decision.transform([toss_decision])[0]
    venue_encoded = label_encoder_venue.transform([venue])[0]
    
    # Combine encoded features into a single array
    input_features = list(toss_winner_encoded.values.flatten()) + [toss_decision_encoded, venue_encoded]
    
    return [input_features]

# List of teams (assuming the order of teams is consistent)
teams = ['Pune Warriors', 
         'Kolkata Knight Riders',
         'Rajasthan Royals',
         'Kochi Tuskers Kerala',
         'Gujarat Lions',
         'Chennai Super Kings', 
         'Delhi Daredevils', 
         'Deccan Chargers', 
         'Delhi Capitals',
         'Mumbai Indians', 
         'Sunrisers Hyderabad', 
         'Rising Pune Supergiants', 
         'Royal Challengers Bangalore', 
         'Kings XI Punjab']

# Initialize label encoders for toss decision and venue
label_encoder_toss_decision = LabelEncoder()
label_encoder_venue = LabelEncoder()

# Label encoding for toss decision and venue
label_encoder_toss_decision.fit(['bat', 'field'])
label_encoder_venue.fit(['home', 'away'])

# Input from the user
toss_winner = input("""Enter the team that won the toss: 
                       Choices:
                       1. Pune Warriors
                       2. Kolkata Knight Riders
                       3. Rajasthan Royals
                       4. Kochi Tuskers Kerala
                       5. Gujarat Lions
                       6. Chennai Super Kings 
                       7. Delhi Daredevils
                       8. Deccan Chargers
                       9. Delhi Capitals
                       10.Mumbai Indians
                       11.Sunrisers Hyderabad
                       12.Rising Pune Supergiants
                       13.Royal Challengers Bangalore
                       14.Kings XI Punjab 
                       """)
toss_decision = input("Enter the toss decision (bat/field): ")
venue = input("Enter the venue (home/away): ")

# Preprocess input data
input_features = preprocess_input(toss_winner, toss_decision, venue)

# Make prediction
prediction = model.predict(input_features)

# Display the result
if prediction == 1:
    print("The team is predicted to win")
else:
    print("The team is predicted to lose")


Enter the team that won the toss: 
                       Choices:
                       1. Pune Warriors
                       2. Kolkata Knight Riders
                       3. Rajasthan Royals
                       4. Kochi Tuskers Kerala
                       5. Gujarat Lions
                       6. Chennai Super Kings 
                       7. Delhi Daredevils
                       8. Deccan Chargers
                       9. Delhi Capitals
                       10.Mumbai Indians
                       11.Sunrisers Hyderabad
                       12.Rising Pune Supergiants
                       13.Royal Challengers Bangalore
                       14.Kings XI Punjab 
                       Royal Challengers Bangalore
Enter the toss decision (bat/field): bat
Enter the venue (home/away): away
The team is predicted to lose


C:\Users\admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(
